# Site settings
title: 235.GG
email: gamingryan235@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ryan's portfolio website. You can see my latest projects and works.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github_username:  gamingryan235

# Build settings
markdown: kramdown
permalink: pretty
